### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by cadriaans** [qinliuliuqin/Medical-Detection3d-Toolkit#1]
Hi, i was wondering if preprocessing of the data is included in this model or if you need to preprocess the ct data yourself?
Like resampling, reshape, alignment and normalization?

**Comment by sunshinelike** [comment]
How to get the landmark.csv with every data in the preprocessing phrase?
Looking forward to your reply. Thank you very much.

**Comment by qinliuliuqin** [comment]
@sunshinelike Hi, sorry for the late response. I overlooked this issue. An example landmark csv file can be found here: [https://github.com/qinliuliuqin/Medical-Detection3d-Toolkit/blob/master/demo/case_17_cbct_patient.csv](https://github.com/qinliuliuqin/Medical-Detection3d-Toolkit/blob/master/demo/case_17_cbct_patient.csv). You need to generate these files by yourself.

**Comment by qinliuliuqin** [comment]
@cadriaans Hi, during training, we will crop, normalize, and resample the image. [https://github.com/qinliuliuqin/Medical-Detection3d-Toolkit/blob/7a7d98debe54604e38cfd5fad8cb50fdd8d028be/detection3d/config/lmk_train_config.py#L56](https://github.com/qinliuliuqin/Medical-Detection3d-Toolkit/blob/7a7d98debe54604e38cfd5fad8cb50fdd8d028be/detection3d/config/lmk_train_config.py#L56). During inference, we take the whole image as input and resample it to the training spacing, and then normalize it. More details please refer to the code.
